# Generated by Django 4.2.4 on 2023-10-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_status_restaurant_bonuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="", max_length=100),
        ),
    ]
